name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            node-version: [14.x, 16.x, 18.x]
            os: [ubuntu-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
